# Optional part: the live lockstep of the frontend classes against Gemmini's RTL (label rtl).
# Verilates the Verilog that rtl/ex/elaborate_ex.sh generated (ExecuteTop, CmdTop, CtrlTop from
# rtl/ex/src/) and builds rtl_fe (rtl/fe_bench.cpp).
#
#   SYSTOLIQUE_FE_VERILOG_DIR  generated Verilog (default ~/opt/gemmini-verilog-709bc56/frontend):
#                              ExecuteTop.v, CmdTop.v, CtrlTop.v, plusarg_reader.v, provenance.json
#   Verilator 5.038            as for rtl/rtl.cmake
#
# Skipped with a warning when Verilator or the Verilog is missing; the stored traces still check
# the model (systolique_fe_trace_<top>).

set(SYSTOLIQUE_FE_VERILOG_DIR "$ENV{HOME}/opt/gemmini-verilog-709bc56/frontend" CACHE PATH
    "Verilog generated by rtl/ex/elaborate_ex.sh")

find_package(verilator 5.0 QUIET NO_DEFAULT_PATH HINTS $ENV{HOME}/opt/verilator-5.038/share/verilator)
if(NOT verilator_FOUND)
  find_package(verilator 5.0 QUIET HINTS $ENV{VERILATOR_ROOT})
endif()
if(NOT verilator_FOUND)
  message(WARNING "systolique: no Verilator 5; skipping the optional frontend RTL lockstep bench "
                  "(the stored traces still check the model)")
  return()
endif()
set(_fe_missing)
foreach(f ExecuteTop.v CmdTop.v CtrlTop.v plusarg_reader.v)
  if(NOT EXISTS ${SYSTOLIQUE_FE_VERILOG_DIR}/${f})
    list(APPEND _fe_missing ${f})
  endif()
endforeach()
if(_fe_missing)
  message(WARNING "systolique: skipping the optional frontend RTL lockstep bench; no generated "
                  "Verilog in ${SYSTOLIQUE_FE_VERILOG_DIR} (missing ${_fe_missing}).\n  Generate it with "
                  "rtl/ex/elaborate_ex.sh (rtl/README.md) or set -DSYSTOLIQUE_FE_VERILOG_DIR=<dir>")
  return()
endif()
message(STATUS "systolique: Gemmini frontend RTL ${SYSTOLIQUE_FE_VERILOG_DIR}")

set(_fe_vargs --x-initial 0 --x-assign 0 -Wno-fatal -Wno-lint -Wno-style +define+STOP_COND=1
              +define+PRINTF_COND=1 +define+RANDOM=0 -O3)
set(_fe_gen ${CMAKE_CURRENT_BINARY_DIR}/verilated/frontend)
add_executable(rtl_fe rtl/fe_bench.cpp)
target_include_directories(rtl_fe PRIVATE ${PROJECT_SOURCE_DIR}/rtl)
target_link_libraries(rtl_fe PRIVATE systolique_bench)
set_source_files_properties(rtl/fe_bench.cpp PROPERTIES COMPILE_OPTIONS "${SYSTOLIQUE_WARNINGS}")
target_include_directories(rtl_fe SYSTEM PRIVATE ${VERILATOR_ROOT}/include ${VERILATOR_ROOT}/include/vltstd
                           ${_fe_gen}/ex ${_fe_gen}/cmd ${_fe_gen}/ctrl)
foreach(top ExecuteTop CmdTop CtrlTop)
  string(TOLOWER ${top} _low)
  string(REPLACE "top" "" _dir ${_low})
  if(_dir STREQUAL "execute")
    set(_dir ex)
  endif()
  verilate(rtl_fe SOURCES ${SYSTOLIQUE_FE_VERILOG_DIR}/${top}.v ${SYSTOLIQUE_FE_VERILOG_DIR}/plusarg_reader.v
           TOP_MODULE ${top} PREFIX V${top} DIRECTORY ${_fe_gen}/${_dir} VERILATOR_ARGS ${_fe_vargs})
endforeach()

set(_fe_ref ${PROJECT_SOURCE_DIR}/tests/reference/gemmini_fe)
# Every output port every cycle: the directed tests (and the RTL must reproduce their stored
# traces), the stored random seeds, then random seeds that are not stored.
add_test(NAME rtl_fe_execute COMMAND rtl_fe --top ExecuteTop --catalog --seeds 200)
add_test(NAME rtl_fe_cmd COMMAND rtl_fe --top CmdTop --catalog --seeds 400)
add_test(NAME rtl_fe_ctrl COMMAND rtl_fe --top CtrlTop --catalog --seeds 60)
foreach(t execute cmd ctrl)
  set_tests_properties(rtl_fe_${t} PROPERTIES LABELS rtl TIMEOUT 3600
    PASS_REGULAR_EXPRESSION "LOCKSTEP [A-Za-z]+ tests=[1-9][0-9]* .* mismatches=0"
    FAIL_REGULAR_EXPRESSION "FAIL|%Error|%Fatal")
endforeach()
foreach(top ExecuteTop CmdTop CtrlTop)
  # the RTL reproduces every stored trace
  add_test(NAME rtl_fe_reference_${top} COMMAND rtl_fe --top ${top} --stored ${_fe_ref}/${top})
  set_tests_properties(rtl_fe_reference_${top} PROPERTIES LABELS rtl TIMEOUT 3600
    PASS_REGULAR_EXPRESSION "LOCKSTEP ${top} tests=[1-9][0-9]* .* mismatches=0" FAIL_REGULAR_EXPRESSION "FAIL")
  # the comparison must see one wrong bit of a model output
  add_test(NAME rtl_fe_fault_${top} COMMAND rtl_fe --top ${top} --catalog --fault)
  set_tests_properties(rtl_fe_fault_${top} PROPERTIES LABELS rtl
    PASS_REGULAR_EXPRESSION "FAIL cycle [0-9]+: [a-z_0-9]+\\[[0-9]+\\]: rtl=0x[0-9a-f]+ model=0x[0-9a-f]+")
endforeach()

if(Python3_FOUND)
  add_test(NAME rtl_fe_verilog
           COMMAND ${Python3_EXECUTABLE} ${PROJECT_SOURCE_DIR}/tools/rtl_provenance.py fe-check-verilog
                   --verilog ${SYSTOLIQUE_FE_VERILOG_DIR})
  set_tests_properties(rtl_fe_verilog PROPERTIES LABELS rtl PASS_REGULAR_EXPRESSION "VERILOG ok")
endif()
