# Optional part: the live lockstep against Gemmini's RTL (label rtl). Verilates the Verilog that
# rtl/elaborate.sh generated from the pinned Gemmini sources and builds one lockstep bench per
# configuration, rtl_<config>, against SystolicArray.
#
#   SYSTOLIQUE_VERILOG_DIR  generated Verilog (default ~/opt/gemmini-verilog-709bc56):
#                           <config>/MeshTop.v, <config>/MeshWithDelaysTop.v,
#                           <config>/correspondence.txt, provenance.json
#   Verilator 5.038         ~/opt/verilator-5.038 first, then VERILATOR_ROOT, then the PATH
#
# Skipped with a warning when Verilator or the Verilog is missing; the stored traces still check
# the model (systolique_trace_<config>).

set(SYSTOLIQUE_VERILOG_DIR "$ENV{HOME}/opt/gemmini-verilog-709bc56" CACHE PATH
    "Verilog generated by rtl/elaborate.sh")

find_package(verilator 5.0 QUIET NO_DEFAULT_PATH
             HINTS $ENV{HOME}/opt/verilator-5.038/share/verilator)
if(NOT verilator_FOUND)
  find_package(verilator 5.0 QUIET HINTS $ENV{VERILATOR_ROOT})
endif()
if(NOT verilator_FOUND)
  message(WARNING "systolique: no Verilator 5 (find_package(verilator)); skipping the optional RTL "
                  "lockstep bench (the stored traces still check the model)")
  return()
endif()

set(_missing)
foreach(cfg ${SYSTOLIQUE_CONFIGS})
  foreach(f MeshTop.v MeshWithDelaysTop.v correspondence.txt)
    if(NOT EXISTS ${SYSTOLIQUE_VERILOG_DIR}/${cfg}/${f})
      list(APPEND _missing ${cfg}/${f})
    endif()
  endforeach()
endforeach()
if(_missing)
  message(WARNING "systolique: skipping the optional RTL lockstep bench; no generated Verilog in "
                  "${SYSTOLIQUE_VERILOG_DIR} (missing ${_missing}).\n  Generate it with "
                  "rtl/elaborate.sh (rtl/README.md) or set -DSYSTOLIQUE_VERILOG_DIR=<dir>")
  return()
endif()
message(STATUS "systolique: Gemmini RTL ${SYSTOLIQUE_VERILOG_DIR}, Verilator ${verilator_VERSION}")

# --x-initial 0 / --x-assign 0: every register starts at 0, as the model assumes (no
# RANDOMIZE_* defines); STOP_COND/PRINTF_COND enable the Chisel assertions ($fatal).
set(_vargs --x-initial 0 --x-assign 0 -Wno-fatal -Wno-lint -Wno-style +define+STOP_COND=1
           +define+PRINTF_COND=1 -O3 --vpi --public-flat-rw)

foreach(cfg ${SYSTOLIQUE_CONFIGS})
  set(_tgt rtl_${cfg})
  set(_gen ${CMAKE_CURRENT_BINARY_DIR}/verilated/${cfg})
  file(MAKE_DIRECTORY ${_gen})
  file(WRITE ${_gen}/rtl_tops.h.in
       "#pragma once\n#include \"Vmesh_${cfg}.h\"\n#include \"Vmwd_${cfg}.h\"\n"
       "using RtlMeshTop = Vmesh_${cfg};\nusing RtlMwdTop = Vmwd_${cfg};\n"
       "#define SYSTOLIQUE_RTL_CONFIG \"${cfg}\"\n")
  configure_file(${_gen}/rtl_tops.h.in ${_gen}/rtl_tops.h COPYONLY)
  add_executable(${_tgt} rtl/rtl_bench.cpp rtl/correspondence.cpp)
  target_include_directories(${_tgt} PRIVATE ${_gen} ${PROJECT_SOURCE_DIR}/rtl)
  target_link_libraries(${_tgt} PRIVATE systolique_bench)
  target_compile_definitions(${_tgt} PRIVATE SYSTOLIQUE_VERILOG_DIR="${SYSTOLIQUE_VERILOG_DIR}")
  # Warnings apply to the project's sources only: Verilator's headers and generated code are
  # system include directories (verilate() also adds them as normal ones; SYSTEM wins).
  set_source_files_properties(rtl/rtl_bench.cpp rtl/correspondence.cpp PROPERTIES
    COMPILE_OPTIONS "${SYSTOLIQUE_WARNINGS}")
  target_include_directories(${_tgt} SYSTEM PRIVATE ${VERILATOR_ROOT}/include
                             ${VERILATOR_ROOT}/include/vltstd ${_gen}/mesh ${_gen}/mwd)
  verilate(${_tgt} SOURCES ${SYSTOLIQUE_VERILOG_DIR}/${cfg}/MeshTop.v TOP_MODULE MeshTop
           PREFIX Vmesh_${cfg} DIRECTORY ${_gen}/mesh VERILATOR_ARGS ${_vargs})
  verilate(${_tgt} SOURCES ${SYSTOLIQUE_VERILOG_DIR}/${cfg}/MeshWithDelaysTop.v
           TOP_MODULE MeshWithDelaysTop PREFIX Vmwd_${cfg} DIRECTORY ${_gen}/mwd
           VERILATOR_ARGS ${_vargs})
  # Every output port every cycle, the internal correspondence through VPI, the stored traces
  # reproduced by the RTL, plus 20 seeds of random tests that are not stored.
  add_test(NAME rtl_${cfg} COMMAND ${_tgt} --check-ref ${SYSTOLIQUE_REF_DIR}/${cfg} --soak 20)
  set_tests_properties(rtl_${cfg} PROPERTIES LABELS rtl TIMEOUT 3600
    PASS_REGULAR_EXPRESSION "LOCKSTEP config=${cfg} .* mismatches=0"
    FAIL_REGULAR_EXPRESSION "FAIL|%Error|%Fatal")
endforeach()

# The correspondence check must see a wrong model value of every kind (tiled has all five).
foreach(kind exact feed resp valid pipev)
  add_test(NAME rtl_corr_fault_${kind} COMMAND rtl_tiled --test os_single)
  set_tests_properties(rtl_corr_fault_${kind} PROPERTIES LABELS rtl
    ENVIRONMENT SYSTOLIQUE_CORR_FAULT=${kind}
    PASS_REGULAR_EXPRESSION "FAIL tiled MeshWithDelaysTop/os_single .*: rtl=[0-9]+ model=[0-9]+")
endforeach()

# The Verilog is the one the stored traces were made from (same Gemmini sources and generator).
if(Python3_FOUND)
  add_test(NAME rtl_verilog
           COMMAND ${Python3_EXECUTABLE} ${PROJECT_SOURCE_DIR}/tools/rtl_provenance.py check-verilog
                   --verilog ${SYSTOLIQUE_VERILOG_DIR} --ref-dir ${SYSTOLIQUE_REF_DIR})
  set_tests_properties(rtl_verilog PROPERTIES LABELS rtl PASS_REGULAR_EXPRESSION "VERILOG ok")
endif()
