// Lockstep bench (optional part, rtl/rtl.cmake): the Verilated Gemmini RTL tops of one
// configuration and SystolicArray get the same inputs every cycle; every output port is compared
// every cycle (values and valid timing) and the run stops at the first difference. Every cycle
// the documented internal correspondence (correspondence.h) is checked through VPI before the
// clock edge, and every run's accounting must conserve (SystolicArray::check). Optionally writes
// the RTL's inputs and outputs as reference traces (bench/trace_io.h).
//
//   rtl_<config> [--test <name>]... [--write-ref <dir>] [--check-ref <dir>]
//                [--comment <text>]... [--no-correspondence] [--soak <n>]
//
// --soak adds n seeds of random tests (soak_tests in bench/stimulus.h) that are not stored.
// --check-ref also requires the RTL's inputs and outputs to equal the stored trace.
//
// Prints one line per test and a summary:
//   LOCKSTEP config=<c> tests=<n> cycles=<n> compared=<n> corr_cycles=<n> corr_values=<n>
//            mismatches=<n>
#include "correspondence.h"
#include "rtl_dut.h"
#include "rtl_tops.h"  // generated by rtl/rtl.cmake: RtlMeshTop, RtlMwdTop, SYSTOLIQUE_RTL_CONFIG
#include "run.h"
#include "stimulus.h"
#include "trace_io.h"

#include "systolique/systolic_array.h"

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>

namespace systolique {
template <>
struct Ports<RtlMeshTop> : MeshPorts<RtlMeshTop> {};
template <>
struct Ports<RtlMwdTop> : MwdPorts<RtlMwdTop> {};
}  // namespace systolique

using namespace systolique;

namespace {

struct RunResult {
  bool ok = true;
  unsigned cycles = 0;            // cycles run (reset included)
  unsigned compared = 0;          // cycles whose outputs were compared
  std::string error;              // first mismatch
  std::vector<Frame> rows;        // per cycle: inputs and the RTL's outputs
};

void clear_inputs(const std::vector<PortSpec> &spec, Frame &f) {
  for (size_t p = 0; p < spec.size(); ++p)
    if (spec[p].input) std::fill(f[p].w.begin(), f[p].w.end(), 0);
}

std::string at_cycle(unsigned cycle, const std::string &what) {
  return "cycle " + std::to_string(cycle) + ": " + what;
}

// Drives `stim` (decided from the RTL's outputs) into the RTL and the model, 4 reset cycles
// first, as the stored traces were made.
template <class V>
RunResult lockstep(const ArrayConfig &cfg, Top top, Stimulus &stim, RtlDut<V> &rtl,
                   SystolicArray &model, Correspondence *cc, unsigned long long &corr_cycles) {
  const auto spec = port_specs(cfg, top);
  const unsigned reset_cycles = 4, max_cycles = 1000000;
  RunResult res;
  rtl.reinit();
  model.reset(0);
  Frame f = make_frame(spec), check = f, mine = f;
  for (unsigned cycle = 0; cycle < max_cycles; ++cycle) {
    rtl.get_outputs(f);  // outputs of this cycle (registers only)
    clear_inputs(spec, f);
    if (cycle < reset_cycles) {
      f[0].set(0, 1, 1);
    } else if (!stim.next(cycle - reset_cycles, f, f)) {
      break;
    }
    rtl.set_inputs(f);
    rtl.eval();
    check = f;
    rtl.get_outputs(check);
    if (check != f) {
      res.ok = false;
      res.error = at_cycle(cycle, "RTL outputs changed with this cycle's inputs: " +
                                      diff_outputs(spec, f, check));
      break;
    }
    mine = f;
    outputs_to_frame(model, top, mine);
    ++res.compared;
    if (const std::string d = diff_outputs(spec, f, mine); !d.empty()) {
      res.ok = false;
      res.error = at_cycle(cycle, d);
      res.rows.push_back(f);
      res.cycles = cycle + 1;
      break;
    }
    frame_to_inputs(model, top, f);
    if (cc) {  // the registers of this cycle, before the edge
      ++corr_cycles;
      if (const std::string e = cc->check(); !e.empty()) {
        res.ok = false;
        res.error = at_cycle(cycle, e);
        res.cycles = cycle + 1;
        break;
      }
    }
    res.rows.push_back(f);
    res.cycles = cycle + 1;
    rtl.edge();
    model.tick();
  }
  if (res.ok && res.cycles >= max_cycles) {
    res.ok = false;
    res.error = "no end after " + std::to_string(max_cycles) + " cycles";
  }
  return res;
}

}  // namespace

int main(int argc, char **argv) {
  std::setvbuf(stdout, nullptr, _IOLBF, 0);
  std::vector<std::string> only, comments;
  std::string ref_dir, check_dir;
  bool corr = true;
  unsigned soak = 0;
  for (int i = 1; i < argc; ++i) {
    const std::string a = argv[i];
    if (a == "--test" && i + 1 < argc)
      only.push_back(argv[++i]);
    else if (a == "--write-ref" && i + 1 < argc)
      ref_dir = argv[++i];
    else if (a == "--check-ref" && i + 1 < argc)
      check_dir = argv[++i];
    else if (a == "--comment" && i + 1 < argc)
      comments.push_back(argv[++i]);
    else if (a == "--no-correspondence")
      corr = false;
    else if (a == "--soak" && i + 1 < argc)
      soak = unsigned(std::atoi(argv[++i]));
    else {
      std::fprintf(stderr, "usage: %s [--test name]... [--write-ref dir] [--check-ref dir] "
                           "[--comment text]... [--no-correspondence] [--soak n]\n", argv[0]);
      return 2;
    }
  }
  const ArrayConfig *cfg = find_config(SYSTOLIQUE_RTL_CONFIG);
  if (!cfg) {
    std::fprintf(stderr, "unknown configuration %s\n", SYSTOLIQUE_RTL_CONFIG);
    return 2;
  }
  VerilatedContext ctx;
  ctx.fatalOnError(false);
  RtlDut<RtlMeshTop> rtl_mesh(ctx, "mesh_top");
  RtlDut<RtlMwdTop> rtl_mwd(ctx, "mwd_top");
  ArrayOptions mesh_if;
  mesh_if.interface = Interface::Mesh;
  SystolicArray model_mesh(*cfg, mesh_if), model_mwd(*cfg);

  auto tests = test_catalog(*cfg);
  const size_t stored_tests = tests.size();  // the soak tests have no stored trace
  for (auto &t : soak_tests(*cfg, soak)) tests.push_back(std::move(t));
  unsigned ntests = 0, failures = 0;
  unsigned long long cycles = 0, compared = 0, corr_cycles = 0, corr_values = 0;
  std::set<std::string> unused;
  for (size_t ti = 0; ti < tests.size(); ++ti) {
    const TestDef &t = tests[ti];
    if (!only.empty() && std::find(only.begin(), only.end(), t.name) == only.end()) continue;
    ++ntests;
    auto stim = t.make(*cfg);
    const bool mesh = t.top == Top::Mesh;
    SystolicArray &model = mesh ? model_mesh : model_mwd;
    std::unique_ptr<Correspondence> cc;
    if (corr)
      cc = std::make_unique<Correspondence>(
          *cfg, t.top, model, mesh ? "mesh_top.MeshTop" : "mwd_top.MeshWithDelaysTop",
          SYSTOLIQUE_VERILOG_DIR "/" SYSTOLIQUE_RTL_CONFIG "/correspondence.txt");
    RunResult r = mesh ? lockstep(*cfg, t.top, *stim, rtl_mesh, model, cc.get(), corr_cycles)
                       : lockstep(*cfg, t.top, *stim, rtl_mwd, model, cc.get(), corr_cycles);
    const bool rtl_failed = mesh ? rtl_mesh.failed() : rtl_mwd.failed();
    if (r.ok && stim->error().empty() == t.expect_stall) {
      r.ok = false;
      r.error = t.expect_stall ? "expected the driver to stall" : stim->error();
    }
    if (rtl_failed && r.ok) {
      r.ok = false;
      r.error = "the RTL stopped ($fatal/assertion)";
    }
    if (r.ok) {  // the PE-cycle accounting of the run conserves
      if (const std::string e = SystolicArray::check(model.accounting()); !e.empty()) {
        r.ok = false;
        r.error = "accounting: " + e;
      }
    }
    if (r.ok && !check_dir.empty() && ti < stored_tests) {  // the RTL still produces the trace
      TraceInfo info;
      std::vector<Frame> stored;
      std::string err;
      if (!read_trace(check_dir + "/" + t.name + ".csv.gz", port_specs(*cfg, t.top), info, stored,
                      err)) {
        r.ok = false;
        r.error = err;
      } else if (stored != r.rows) {
        size_t c = 0;
        while (c < stored.size() && c < r.rows.size() && stored[c] == r.rows[c]) ++c;
        r.ok = false;
        r.error = "the RTL differs from the stored trace from cycle " + std::to_string(c);
      }
    }
    cycles += r.cycles;
    compared += r.compared;
    if (cc) {
      corr_values += cc->values_checked();
      unused.insert(cc->unused().begin(), cc->unused().end());
    }
    if (!r.ok) ++failures;
    std::printf("%s %s %s/%s cycles=%u compared=%u%s%s\n", r.ok ? "PASS" : "FAIL",
                SYSTOLIQUE_RTL_CONFIG, top_name(t.top), t.name.c_str(), r.cycles, r.compared,
                r.ok ? "" : " ", r.ok ? "" : r.error.c_str());
    if (r.ok && !ref_dir.empty() && ti < stored_tests) {
      TraceInfo info;
      info.comments.push_back("systolique Gemmini RTL reference trace: " +
                              std::string(top_name(t.top)) + " config=" SYSTOLIQUE_RTL_CONFIG
                              " test=" + t.name);
      info.comments.push_back(t.what);
      for (const auto &c : comments) info.comments.push_back(c);
      std::string err;
      const std::string path = ref_dir + "/" + t.name + ".csv.gz";
      if (!write_trace(path, port_specs(*cfg, t.top), info, r.rows, err)) {
        std::fprintf(stderr, "%s\n", err.c_str());
        return 1;
      }
    }
  }
  if (!unused.empty()) {
    std::map<std::string, unsigned> pats;  // by pattern: digits as '*'
    for (const auto &n : unused) {
      std::string pat;
      for (char ch : n)
        if (!(std::isdigit(static_cast<unsigned char>(ch)) && !pat.empty() && pat.back() == '*'))
          pat += std::isdigit(static_cast<unsigned char>(ch)) ? '*' : ch;
      ++pats[pat];
    }
    std::string u;
    for (const auto &p : pats) u += " " + p.first + " (" + std::to_string(p.second) + ")";
    std::printf("NOTE model registers the FIRRTL compiler removed from the RTL (unread):%s\n",
                u.c_str());
  }
  std::printf("LOCKSTEP config=%s tests=%u cycles=%llu compared=%llu corr_cycles=%llu "
              "corr_values=%llu mismatches=%u\n", SYSTOLIQUE_RTL_CONFIG, ntests, cycles, compared,
              corr_cycles, corr_values, failures);
  return failures || ntests == 0 ? 1 : 0;
}
